# Generated by Django 4.2.1 on 2023-05-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_productspecification_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(choices=[('weight', 'Масса'), ('volume', 'Объем')], max_length=100),
        ),
    ]
