# Generated by Django 4.2.1 on 2023-05-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_productspecification_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(choices=[('weight', 'Масса'), ('volume', 'Объем')], max_length=100),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
