# Generated by Django 4.2.1 on 2023-05-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_productspecification_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='percent',
        ),
    ]
