# Generated by Django 4.2.1 on 2023-05-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_customer_product_in_cart_alter_cart_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
