# Generated by Django 4.2.1 on 2023-05-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_productreview_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
