# Generated by Django 4.2.1 on 2023-05-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
