# Generated by Django 4.2.1 on 2023-05-12 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_categoryproduct_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproduct',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoryproduct'),
        ),
    ]
