# Generated by Django 4.2.1 on 2023-05-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_categoryproduct_slug_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='product',
            new_name='product_reviewed',
        ),
        migrations.AddField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='api.productreview'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(choices=[('weight', 'Масса'), ('volume', 'Объем'), ('items', 'Штук')], max_length=100),
        ),
    ]
