# Generated by Django 4.2.1 on 2023-05-12 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_product_productreview_product_reviewed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product_reviewed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.product'),
        ),
    ]
