# Generated by Django 4.2.1 on 2023-05-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_productreview_product_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
