# Generated by Django 4.2.1 on 2023-05-13 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0033_product_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(help_text='Номер телефона', max_length=20)),
                ('delivery_type', models.CharField(choices=[('basic_delivery', 'Доставка'), ('express_delivery', 'Экспресс-доставка')], max_length=100)),
                ('city', models.CharField(help_text='Город доставки', max_length=100)),
                ('address', models.CharField(help_text='Адрес доставки', max_length=500)),
                ('payment_types', models.CharField(choices=[('card_online', 'Онлайн картой'), ('any_account', 'Онлайн со случайного чужого счёта')], max_length=100)),
                ('status', models.CharField(choices=[('not_paid', 'Не оплачен'), ('paid', 'Оплачен'), ('pay_error', 'Ошибка оплаты')], max_length=100)),
                ('total_cost', models.FloatField(default=0, help_text='Общая стоимость товаров в заказе')),
                ('products', models.ManyToManyField(blank=True, to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
