# Generated by Django 4.2.1 on 2023-05-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, help_text='Адрес доставки', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, help_text='Город доставки', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('basic_delivery', 'Доставка'), ('express_delivery', 'Экспресс-доставка')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_types',
            field=models.CharField(blank=True, choices=[('card_online', 'Онлайн картой'), ('any_account', 'Онлайн со случайного чужого счёта')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, help_text='Номер телефона', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('not_paid', 'Не оплачен'), ('paid', 'Оплачен'), ('pay_error', 'Ошибка оплаты')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.FloatField(blank=True, default=0, help_text='Общая стоимость товаров в заказе'),
        ),
    ]
