# Generated by Django 4.2.1 on 2023-05-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('ordinary', 'Доставка'), ('express', 'Экспресс-доставка')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_types',
            field=models.CharField(blank=True, choices=[('online', 'Онлайн картой'), ('someone', 'Онлайн со случайного чужого счёта')], max_length=100),
        ),
    ]
