# Generated by Django 4.2.1 on 2023-05-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_customer_avatar_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.PositiveIntegerField(blank=True, default=99999999999),
        ),
    ]
