# Generated by Django 4.2.1 on 2023-05-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_categoryproduct_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='api.categoryproduct'),
        ),
    ]
