# Generated by Django 4.2.1 on 2023-05-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_categoryproduct_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
